### ISSUE TITLE
Creating a new or editing an existing database table should update Algolia index

### ISSUE THREAD

**Issue by richardxia** [ShelterTechSF/gcloud#8]
If you create a new model instance or update an existing model instance, the changes are not synced to Algolia. We should be calling `instance.reindex!` as described in https://www.algolia.com/doc/api-client/rails/indices/?language=rails#manual-indexing. We should also be removing deleted objects from the index, and we probably want a periodic task to reindex everything.

Also now that I think about it, we should also have the full reindex task skip any objects that are "inactive".

**Comment by cliffcrosland** [comment]
Cool. I created a separate ticket for the hourly full Algolia reindexing task: https://github.com/ShelterTechSF/gcloud/issues/9

This is live on staging and production 😄

**Comment by cliffcrosland** [comment]
Right on. This is already done. See this block in ChangeRequestsController:
```
    if Rails.configuration.x.algolia.enabled
      # Update Algolia index for both the resource and all its services
      change_request.resource&.index!
      change_request.resource&.services.each &:index!
    end
```

Each change request should reindex the appropriate resource and services in Algolia 😄

**Comment by richardxia** [comment]
> @richardxia That sounds great. As we transition to using Helm, I was thinking about removing the k8s template from my askdarcel-api PR and simply adding the Algolia reindex CronJob to the gcloud repository like so:
>
> #7
>
> Any thoughts?

If we switch to Helm, it's going to add one level of indirection, and we may want to put the different "layers" in different repos. With Helm, you can create package, which they call a chart, and when you deploy, you combine a chart with a parameters file (`values.yaml`). The same chart can be reused for multiple different deployment environments by using separate `values.yaml` files.

The `values.yaml` files probably belong in the `gcloud` repo, since that's where we can capture the different parameters for different environments, but it might be a good idea to keep the chart definition itself in the same repositories as the application code.
